theme: minima
title: One Hundred
description: "A console-mode implementation of a simple form of the mathematical game _Nim_."
author:
  name: Nick Bennett
  email: nick@nickbenn.com
titles_from_headings:
  enabled: false
