title: One Hundred
titles_from_headings:
  enabled: false
author:
  name: Nick Bennett
  email: nick@nickbenn.com
minima:
  skin: solarized
  social_links:
    github: nick-bennett
    linkedin: nickbenn
header_pages:
  - api/index.html
remote_theme: jekyll/minima
