remote_theme: jekyll/minima

title: One Hundred
titles_from_headings:
  enabled: false
author:
  name: Nick Bennett
  email: nick@nickbenn.com
minima:
  skin: solarized
  social_links:
    - platform: github
      user_url: https://github.com/nick-bennett
    - platform: linkedin
      user_url: https://www.linkedin.com/in/nickbenn/
header_pages:
  - api/index.html
